[tool.poetry]
name = "netmikro"
version = "0.1.0"
description = ""
authors = ["Henrique Sebastião <henriquesebastiao.web@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
netmiko = "^4.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.1"
pytest-cov = "^4.1.0"
blue = "^0.9.1"
isort = "^5.12.0"
ruff = "^0.0.287"
taskipy = "^1.12.0"

[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.2.8"
mkdocstrings = "^0.23.0"
mkdocstrings-python = "^1.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.ruff]
line-length = 79

[tool.taskipy.tasks]
lint = "ruff . && blue --check --diff . && isort --check --diff ."
format = 'blue .  && isort .'
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -s -x --cov=notas_musicais -vv"
post_test = "coverage html"
